### ISSUE TITLE
[Crash]: setup failed 

### ISSUE THREAD

**Issue by tenzedkariyu19** [Fuzss/blockrunner#10]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.4

### Mod Version (Required)

v6.0.0

### Notes (Required)

i launched the game and it just fails the setup I have both puzzle lib and block runner up to date. I've reloaded like 10 times.

puzzle lib ver is v6.0.7

### Crash Report (Required)

https://paste.modularity.gg/paste/?content=https://cdn.discordapp.com/attachments/1101396706861531157/1112149154181947402/crash-2023-05-27_15.41.02-fml.txt&raw=false

### latest.log (Optional)

https://paste.modularity.gg/paste/?content=https://cdn.discordapp.com/attachments/1101396706861531157/1112149153796083772/latest.log&raw=false

**Comment by Fuzss** [comment]
Fixed in Puzzles Lib v6.0.8.
