### ISSUE TITLE
[Bug]: Doesn't work with Macaw's Paths and Pavings

### ISSUE THREAD

**Issue by TwinMinds** [Fuzss/blockrunner#12]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

v3.0.2-1.18.2-Forge

### Notes (Required)

Currently, I am able to add path blocks from Macaw's Paths and Pavings mod, and the speed bonus is visibly reflected in JEI but doesn't actually apply the speed bonus when walking on the paths.

I read up on the closed issues and found this exact issue was fixed in later versions, but those later versions aren't available on 1.18.2.  Is it possible to backport that fix to 1.18.2 so we can have partial blocks affected by this mod?

**Comment by Fuzss** [comment]
Should work now in v3.1.0, the system is the same in that version as in 1.20+.
