### ISSUE TITLE
[Bug]: FOV juddering with Parcool

### ISSUE THREAD

**Issue by Baggytrousers27** [Fuzss/blockrunner#5]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

BlockRunner-v4.2.0-1.19.2-Forge

### Notes (Required)

Forge 43.1.27
PuzzlesLib-v4.3.4-1.19.2-Forge
BlockRunner-v4.2.0-1.19.2-Forge
ParCool-1.19.2-1.0.0.2-R

Running on path blocks, different types of stone blocks (for example the patterned stone floors in dungeon crawl dungeons) etc. causes the fov to rapidly shudder forward and back regardless of whether FOV effects are switched off in the config.

![juddering](https://user-images.githubusercontent.com/15883796/192561809-2daa84f5-3d7c-4634-85e8-bf34514f5c55.gif)

### latest.log (Optional)

https://gist.github.com/Baggytrousers27/833633cf3468459c7607ace577b40eb1

**Comment by Fuzss** [comment]
Is this still an issue in v4.2.1?
