### ISSUE TITLE
[Bug]: Block Runner replaces FOV effect accessibility option

### ISSUE THREAD

**Issue by Aulberon** [Fuzss/blockrunner#6]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.0

### Notes (Required)

Block Runner apparently overrides the FOV Effect option, causing it to not work.
If using Block Runner, no matter what position the FOV effect slider is set to, the FOV effect will always be displayed in full effect, except when running over a path.
Changing the option in the mod to change the fov while running on a path does not change this behavior.

**Comment by Fuzss** [comment]
Should be fixed in v4.2.1.
