### ISSUE TITLE
[Suggestion]: Tag for blocks with speed boost

### ISSUE THREAD

**Issue by MarioSMB** [Fuzss/blockrunner#8]
### Suggestion (Required)

It's becoming increasingly noticeable that the current configuration design just isn't expansible - several mods add path blocks that need to be manually defined in the file, each needing to also include a speed value and to be loaded for it to all work.  

With that said, I'd like to suggest a somewhat radical design change; have the configuration file define a *default* speed value for blocks included in a new **block tag** associated with the mod.  
This will make support much easier for modpack developers (and fellow mod developers) as a simple tag could be included via datapacks. Fine-control over block types could still be added if so desired by making use of subcategories (e.g. block_runner:quick_blocks/path), allowing the config to adjust the speed based on these categories, though I suspect a global setting may be good enough in most use cases!

**Comment by MarioSMB** [comment]
This might be easier than I first thought; the config file could look something like this (probably not exactly depending on how flexible it should be):  
```
{
  "#blockrunner:paths": 1.25,
  "#blockrunner:stone_blocks": 1.25
}
```
Even though this can be done as a user, I strongly recommend making default tags so that mods and modpacks with path blocks and such can add automatic support for your mod.

**Comment by Fuzss** [comment]
The last suggestion is exactly how the config works already. Just that there are no default tags. 

And speaking of default tags, I‘m not sure they are necessary. There usually isn‘t much point in thinking about mod compat for projects with less than something like 5M downloads, nobody really cares and is gonna use the compat/api. The inconvenience for the user to just adjust this manually is neglegtible.

**Comment by MarioSMB** [comment]
My suggestion doesn't take away user freedom or convenience so much as adding more (and especially making it easier for modpack developers to support your mod) - sure, this is a small mod, but it does something incredibly useful, and almost 300k downloads is nothing to scoff at!

**Comment by Fuzss** [comment]
Added a few default tags as suggested in v4.2.1.
