### ISSUE TITLE
[Suggestion]: Client-side prediction of speedy effect

### ISSUE THREAD

**Issue by MarioSMB** [Fuzss/blockrunner#9]
### Suggestion (Required)

When playing with high latency it becomes very apparent that the speed effect from blocks is handled as a server-side stat, as the speedy effect can appear to occur much later on the player's screen than when they touched the blocks.  
Understandably this might not be an easy one to solve, just thought I'd put the suggestion out there!

**Comment by Fuzss** [comment]
I made some small changes which could potentially fix this, but I can't properly test if the fix was successful. Either way this seems to be the best I can do.
